---
title: POL 182 - Introduction to Research Methods
subtitle: The Science of Politics
author: Prof. O'Geen
institute: Department of Political Science, Davidson College
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
class: inverse, center, middle
```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```
# Get Started

---

# Types of Questions and Answers

- Normative theory or social science  

- Is health care a right or a responsibility?  

- What is the optimal implementation method?

---

# Characteristics of Scientific Research

1. Procedures are public  

--

2. Conclusions are uncertain  

--

3. Inferences  

--

4. The content is the method  

---
class: inverse, center, middle
# Modeling As a Tool

---
# Uses for Statistical Models

 - Description  
 
 - Classification and Prediction  
 
 - Anticipating consequences

---
# Observation and Knowledge

 - Observation is unreliable  
 
 - Isolating causal effects  
 
 - Fundamental problem of causal inference  
 
 - Better to be systematic

---
# What Are We Doing?

 - Describing and interpreting variation
 
 - One variable or relationships
 
 - Math!  
 
 - Infererences about politics, society, the world, etc. 

---
# How Do We Know If We Are Doing It Right?

 - Reliability as a metric  
 
 - Subjectivity is always there  
 
 - Know your limits
 
---
class: inverse, center, middle
# The Heart of the Matter

---
class: center, middle

How do we use **samples** to make **confident** statements about entire **populations**?

---
# Final Words of Warning

1. Samples cannot tell us anything with certainty.  

2. Systematic mistakes in collecting our samples can ruin our results.

---
class: inverse, center, middle

What are your questions?


 